spring.application.name=doitnow
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27018/doitnow
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

app.cors.allowed-origins=http://localhost:4200
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=Content-Type,Authorization,X-Requested-With,Origin,Accept
app.cors.max-age=3600