@baseUrl = http://localhost:8080/api/tasks


### Création de tâche
# @name createTask
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{jwt}}


{
  "title": "Apprendre .NET",
  "description": "Coder une application REST",
  "tags": ["Microsoft", ".NET"]
}

> {% client.global.set("taskId", response.body.id); %}

### Obtenir toutes les tâches
# @name getAllTasks
GET {{baseUrl}}
Accept: application/json
Authorization: Bearer {{jwt}}

### Obtenir le détail d'une tâche
# @name findOneTask
GET {{baseUrl}}/{{taskId}}
Accept: application/json
Authorization: Bearer {{jwt}}

### Obtenir une tâche non existante
# @name findNonExistentTask
GET {{baseUrl}}/99999
Accept: application/json
Authorization: Bearer {{jwt}}

> {%

    client.test("FIND By ID retourne 404", function(){
        client.assert(response.status === 404, "Attendu 404", "reçu " + response.status)
    })
%}

### Mise à jour d'une tâche
# @name updateTask
PUT {{baseUrl}}/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Apprendre Spring Boot",
  "description": "Coder une application REST complète",
  "completed": true
}

### Mise à jour d'une tâche non existante
# @name updateNonExistentTask
PUT {{baseUrl}}/99999
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Apprendre Spring Boot",
  "description": "Coder une application REST complète",
  "completed": true
}

> {%

    client.test("UPDATE retourne 404", function(){
        client.assert(response.status === 404, "Attendu 404", "reçu " + response.status)
    })
%}

### Suppression d'une tâche
# @name deleteTask
DELETE {{baseUrl}}/{{taskId}}
Authorization: Bearer {{jwt}}

### Suppression d'une tâche inexistante
# @name deleteNonExistentTask
DELETE {{baseUrl}}/99999
Authorization: Bearer {{jwt}}

> {%

    client.test("DELETE retourne 404", function(){
    client.assert(response.status === 404, "Attendu 404", "reçu " + response.status)
})
%}
